### ISSUE TITLE
Pagination - response.url check count

### ISSUE THREAD

**Issue by Halama** [keboola/generic-extractor#16]
Zendesk konfigurace využívající stránkování `response.url` a volající resource https://developer.zendesk.com/rest_api/docs/core/incremental_export#incremental-ticket-export 
u zendesk účtu kde je velká aktivita failuje na `Too recent start_time. Use a start_time older than 5 minute`.

```
{
  "parameters": {
    "api": {
      "authentication": {
        "type": "basic"
      },
      "baseUrl": "https://keboola.zendesk.com/api/v2/",
      "pagination": {
        "method": "response.url",
        "urlKey": "next_page"
      }
    },
    "config": {
      "id": "zendesk",
      "username": "tech.support@keboola.com/token",
      "password": "",
      "http": {
        "headers": {
          "Accept": "application/json"
        }
      },
      "jobs": [
        {
          "endpoint": "incremental/tickets",
          "dataType": "tickets",
          "dataField": "tickets",
          "params": {
            "start_time": "1459468800"
          },
          "children": [
            {
              "endpoint": "tickets/{id}/metrics",
              "dataType": "ticket_metric",
              "dataField": "ticket_metric",
              "recursionFilter": "status!=deleted",
              "placeholders": {
                "id": "id"
              }
            }
          ]
        }
      ]
    }
  }
}
```

![image](https://cloud.githubusercontent.com/assets/903531/14488475/c9aea874-0168-11e6-81b8-65b3f6d4c62c.png)

Podle dokumentace zendesk api by se to mělo ošetřit:

When paginating through an incremental export result set, use the count property to determine when to stop. These endpoints return up to 1000 items per page. If count is less than 1000, then stop paginating. Otherwise, use the next_page URL to get the next page of results.

Odpověď api vypadá:

```json
{
  "end_time": 1383685952,
  "next_page": "https://{subdomain}.zendesk.com/api/v2/incremental/tickets.json?start_time=1383685952",
  "count": 1,
  "tickets": [
    {
      "url": "https://{subdomain}.zendesk.com/api/v2/tickets/1.json",
      "id": 2,
      "created_at": "2012-02-02T04:31:29Z",
      "generated_timestamp": 1390362285
      ...
     },
     ...
  ]
}
```

Stránkovadlo by teda mělo fungovat asi takhle:
```
 if response.count < 1000
  return false
 else
  return nextPageUrl
```
Takže do konfigurace stránkování https://github.com/keboola/generic-extractor#responseurl by bylo potřeba zadat asi něco jako:
 - countKey  - cesta k poli kde je uložený počet záznamu. V tomhle případě `count`
 - countThreshold - počet záznamů při kterém použije nextPage. V tomhle případě 1000 

Je to teda asi super neuniverzální :)

Související issue https://keboola.zendesk.com/agent/tickets/4734

Pokud budeme chtít publikovat zendesk ex nad genericem budeme to muset vyřešit.

**Comment by Halama** [comment]
Mozna bych to udelal jako novy typ strankovani pojemnovany treba Zendesk misto rozsireni response.url strankovani. Ciste kvuli srozumitelnosti dokumentace - nebudou pribyvat nejake obskurni parametry davajici smysl zrejme pro jedno API.

**Comment by padak** [comment]
To je jak ten GitHub :) Taky jsem ráno Kachnovi navrhoval udělat stránkování GitHub :-)

**Comment by Halama** [comment]
jj vsechno co tam popisujes bude v podstate sedet i na ten zendesk.

**Comment by kacurez** [comment]
tak Matejkys reportoval podobny problem a poradilo som mu to urobit v oddelenom konfigu s nastavenim paginacie metodou `pagenum` a hlasi ze to funguje:
```
 "pagination": {
        "method": "pagenum",
        "pageParam": "next_page",
        "limit": 1000,
        "limitParam": "count"
      }
```

**Comment by padak** [comment]
@kacurez na jakým api?

**Comment by Halama** [comment]
zendesk, ty jo to vypada ze by tomhlo resit vubec jsem si nevsiml ze tam tohle strankovani uz je

**Comment by Halama** [comment]
@kacurez a pro ty ostatni resource tohle nove strankovani nefungovalo?

**Comment by Halama** [comment]
jo tak to vypada ze pro zendesk by bylo potreba pro obyc api cally to next page strankovadlo https://developer.zendesk.com/rest_api/docs/core/introduction#pagination a pro increment export ten pagnum https://developer.zendesk.com/rest_api/docs/core/incremental_export

Takze feature request asi nakonec pro tenhle pripad zni podpora ruznych strankovani pro ruzne endpointy.

**Comment by kacurez** [comment]
@Halama jj by bolo dobre umoznit strankovanie per endpoint.

Tu je ten matejkysov konfig pre inkrementalne stahovanie ticketov zo zendesku, pre ostatne resource to strankovanie neskusal ale to asi neide imho(ma to v oddelenom konfigu):

```
{
  "parameters": {
    "api": {
      "authentication": {
        "type": "basic"
      },
      "baseUrl": "..zendesk.com/api/v2/",
      "pagination": {
        "method": "pagenum",
        "pageParam": "next_page",
        "limit": 1000,
        "limitParam": "count"
      }
    },
    "config": {
      "debug": true,
      "id": "zendesk_increment",
      "username": "meno",
      "password": "hesielko",
      "http": {
        "headers": {
          "Accept": "application/json"
        }
      },
      "jobs": [
        {
          "endpoint": "incremental/tickets",
          "dataType": "tickets",
          "dataField": "tickets",
          "params": {
            "start_time": 1420070400
          },
          "children": [
            {
              "endpoint": "tickets/{id}/metrics",
              "dataType": "ticket_metric",
              "dataField": "ticket_metric",
              "recursionFilter": "status!=deleted",
              "placeholders": {
                "id": "id"
              }
            }
          ]
        }
      ]
    }
  }
}
```

**Comment by kachnitel** [comment]
Tohle ted relativne cerstve ex umi: https://github.com/keboola/generic-extractor#multiple

**Comment by kachnitel** [comment]
Jinak kdyz pouzijes vsude stejne strankovani, ale mas treba jinou velikost stranky, tak kdyz u endpointu v params pretizis ten limit parametr (treba `count` tady), tak to bude delat 
```
if response.count < 1000
  return false
 else
  return nextPageUrl
``` 
s tim count, co bude v tom parametru, a ten 1000 z pagination bude default, kdyz tam ten count neni. Myslim, ze tim by to melo byt vse pokryte, kdyz ten limit parametr bude jiny, da se pouzit ten `multiple` scroller.

**Comment by ErikZigo** [comment]
@kachnitel Ten generic ma v sobe nejakou ochranu proti nekonecny smycce? Pokud mi dve url vrati stejnou odpoved, ze ten generic skonci?

**Comment by ErikZigo** [comment]
@kacurez Podle me je ten matejkysuv kod nesmysl.

Zadny pagenum strankovani v ZD neni.
Porad mu to bude vracet stejny vysledek, nezavisle na page parametru. Kachna tam ma asi nejakou ochranu proti nekonecny smycce :-)
A proto si matejkys mysli, ze mu to funguje spravne

**Comment by kacurez** [comment]
@ErikZigo niesom si isty ci tomu chapem ale pagenum je metoda ex-generic ktorou sa implementuje strankovanie u ZD inkrementalneho exportu ticketov cez `next_page ` a `count` parametre:
https://developer.zendesk.com/rest_api/docs/core/incremental_export#pagination

**Comment by ErikZigo** [comment]
@kacurez  `next_page ` je URL adresa, ne cislo. A zadny parametr `count` pro strankovani neexistuje.

`count` ti vraci odpoved ze serveru

![image](https://cloud.githubusercontent.com/assets/1726727/15365559/fda8a638-1d20-11e6-8792-abf8778bd0e8.png)

**Comment by ErikZigo** [comment]
Matejkysuv mapping bude volat:

`start_time= 1420070400&next_page=1&count=1000`

`start_time= 1420070400&next_page=2&count=1000`

a pak skonci

**Comment by ErikZigo** [comment]
Server ale vzdycky vrati tech samych 1000 zaznamu

**Comment by kacurez** [comment]
jasne takze ex-generic pouziva `next_page` ako cislo a nie url na dalsiu stranku, takze ako pises: ex-generic nepodporuje inkrement strankovanie ZD.
diky

**Comment by ErikZigo** [comment]
Tohle zaviram, pro zendesk jsme udelali vlastni typ strankovani.

Obdobne to bude i u facebooku
