### ISSUE TITLE
Divné chování v dedikované komponentě

### ISSUE THREAD

**Issue by padak** [keboola/generic-extractor#18]
Ahoj @kachnitel !

Mám Generic Ex s [cfg Slacku](https://connection.keboola.com/admin/projects/901/extractors/ex-generic-v2/slack-12) a funguje OK!
Mám Generic Ex [jako Slack](https://connection.keboola.com/admin/projects/901/extractors/keboola.ex-slack/lololo-63) (keboola.ex-slack) a v něm to netahá všechny data (struktura sedí, jen jich je podstatně méně).

Co jsem udělal pro ověření:

1. vyresetoval state genericu i slacku na 1451606400 (1.1.2016)
2. pustil jsem [generic](https://connection.keboola.com/admin/projects/901/jobs/184531803) a stáhl 3.5MB - to je dobře
3. pustil jsem [slack](https://connection.keboola.com/admin/projects/901/jobs/184531957?q=) a stáhl 406kB - schází mi tady data :(

Přepnul jsem Slack do debug modu [cfg](https://connection.keboola.com/admin/projects/901/extractors/keboola.ex-slack/lololo-63) a vidím, že nestránkuje - vezme každej kanál jen jednou. Příklad kanálu "Zendesk", který má Slack ID `C02CFRNRD` - v jobu bodu "3" je jednou a v "2" je asi dvacetkrát.

Napadlo mě, že Slack ex co jede na oauth bude mít jinej scope, co by ho nějak třeba omezil, ale to by ho omezil jen pro výpis kanálů a ne zpráv v nich, navíc když jsem si přes ruční zavolání 

```
https://syrup.keboola.com/oauth-v2/authorize/keboola.ex-slack
```

sehnal xoxp-xxx token, tak mi v REST klientu vrací pro Zendesk kanál 1000 zpráv normálně = i ten job s bodu "3" by měl dostat víc jak 1000 zpráv a tím pádem i stránkovat. Ten generickej jsem navíc zkusil pustit s tokenem co mi vrací syrup oauth a tahá správné množství dat.

Nevím si s tím rady, oba extraktory fungují OK, generickej jsem postavil a pak jen z něj udělal dedikovanej. Neměl by se ničím lišit :(

Any clue?

**Comment by kachnitel** [comment]
Ahoj!
query` v `api` je deprekovany objekt, protoze byl matouci, pouzity ​*jen*​ s `authentication.type = url.query`, kus mi toho zbyl v dokumentaci. No a jelikoz jsi v ex-generic pouzil url.query, posilal se ti parametr `count`, ale ve slack jsi mel oauth a tak se count neposlal => prisla default velikost stranky a tak bylo pole mensi nez 1000, s cimz pocitas ve strankovani. 

Opravil jsem to v dokumentaci a upravil sablonu, aby to fungovalo.

**Comment by padak** [comment]
hustě! na tohle bych nikdy nepřišel, díky!
