### ISSUE TITLE
documentation: rewrite yaml examples to json

### ISSUE THREAD

**Issue by kacurez** [keboola/generic-extractor#28]
Generic sa konfiguruje v jsone ale example ma v yaml co dost ludia mate.

**Comment by odinuv** [comment]
WIP https://github.com/keboola/developers-docs/tree/master/extend/generic-extractor

**Comment by odinuv** [comment]
Solved https://github.com/keboola/developers-docs/commit/bb492feb4d3fcdd044a9c9f71fb12f772d35e9db
