### ISSUE TITLE
Upraviť dokumentáciu

### ISSUE THREAD

**Issue by SvetlanaM** [keboola/generic-extractor#30]
Ahoj, super práca, ale tá dokumentácia by sa zišla trochu upraviť. Pripadá mi to ako konfigurácia jsonu pre bower alebo grunt zápisy. No v dokumentácii nie sú jednotné úvodzovky, viem že je to jedno aké sa použijú, ale bolo by fajn to zjednotiť, vymazať stade sekcie s todo, keď nie sú popísané, načo tam sú, zjednotiť, bud to bude zapísané v jsone alebo v yaml, nie všade v dokumentácii mi je jasné, kde sa očakáva dictionary a kde array, funkcie by som dala asi na začiatok a ku každému typu nastavenia by bolo fajn dať full example, nie iba tak začatý niekde a presunúť to možno do sekcie wiki tu na githube a logickejšie to rozčleniť

**Comment by Halama** [comment]
jj souhlas. Dokumentace je wip tady https://developers.keboola.com/extend/generic-extractor/config/ ale zatim je to  asi jenom copy paste, vsem co pises by to melo pak fixnout. Json v jednotnem formatu, full examples atd....

**Comment by SvetlanaM** [comment]
ďakujem, idem to pozrieť

**Comment by odinuv** [comment]
Solved https://github.com/keboola/developers-docs/commit/bb492feb4d3fcdd044a9c9f71fb12f772d35e9db
