### ISSUE TITLE
vendor a docker-compose image

### ISSUE THREAD

**Issue by kachnitel** [keboola/generic-extractor#31]
- Kdyz sem mel aktualni vendor, tak ho to nejdriv pri vytvareni image maze a zarve ze tam je uncommited changes v jednom balicku (i kdyz predem smazu vendor a nainstaluju pres composer install). 
- Kdyz vendor smazu a necham pro vytvoreni image smazany, v image se vytvori a nainstaluje jak ma, ale pak to nejde spustit, ze nevidi "code/vendor/autoload.php". Kdyz si ale pak lokalne udelam composer install, tak se to spusti. Cili to hleda autoload v mym vendoru, ktery ale nemuzu mit, kdyz vytvarim image, aby se vytvoril be chyby.

**Comment by ErikZigo** [comment]
Muzes zkopirovat tu hlasku, co ti to pise?

**Comment by odinuv** [comment]
No myslim, ze je potreba udelat tam `dockerignore` ve kterym bude ten adresar vendor, aby se neposilal do buildovani image. Potom bude spravne fungovat `docker-compose up --build` a bude jeden vendor uvnitr image a druhy vendor muzes mit venku (pro PhpStorm). Druha moznost je spustit ten `composer install` ne pri buildu image, ale pred spustenim (az kdyz je namapovany adresar /code/, ale to by chtelo asi vic predelat).

**Comment by odinuv** [comment]
v docker-compose jsou ted specialne lokalni testy, ktere to hladce resi 76657b3d7f495d49a1c0b38c1bd0d065658ad38e
