### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by jiritobolka** [keboola/generic-extractor#4]
We're trying to get data from Hubspot but for Contacts (for example) we want to download all contacts, but always getting only 500 contacts which is page limit I would say...

`
{
  "parameters": {
    "api": {
      "baseUrl": "https://api.hubapi.com",
      "authentication": {
        "type": "url.query"
      },
      "query": {
        "hapikey": {
          "attr": "hkey"
        }
      },
      "pagination.method": "offset"
    },
    "config": {
      "outputBucket": "ex-hubspot",
      "id": "Hubspot",
      "hkey": "HKEY",
      "http": {
        "headers": {
          "Accept": "application/json"
        }
      },
      "jobs": [
        {
          "endpoint": "contacts/v1/lists/all/contacts/all?count=1000&offset=0",
          "dataType": "contacts",
          "dataField": "contacts"
        }
      ]
    }
  }
}
`

How can I get all records or how can I get the extractor to iterate through pages and return all values, is it supported? Or do we just miss something? Thanks!

**Comment by kachnitel** [comment]
Hello,
it might be somewhat unclear in the documentation, I tried updating the example a little bit, here's what the configuration should look like:

```
{
  "parameters": {
    "api": {
      "baseUrl": "https://api.hubapi.com",
      "authentication": {
        "type": "url.query"
      },
      "query": {
        "hapikey": {
          "attr": "hkey"
        }
      },
      "pagination": {
        "method": "offset",
        "limit": 1000,
        "limitParam": "count",
        "offsetParam": "offset"
      }
    },
    "config": {
      "outputBucket": "ex-hubspot",
      "id": "Hubspot",
      "hkey": "HKEY",
      "http": {
        "headers": {
          "Accept": "application/json"
        }
      },
      "jobs": [
        {
          "endpoint": "contacts/v1/lists/all/contacts/all",
          "dataType": "contacts",
          "dataField": "contacts"
        }
      ]
    }
  }
}
```

Let me know if it works according to expectations!

**Comment by zimami** [comment]
Hi kachnitel,
thanks for your quick response, but it helps just partly. The main core of the problem is in a limit from Hubspot. 

We have more than 10,000 records, but through one call of  "endpoint": "contacts/v1/lists/all/contacts/all" we can download just 100 records according to http://developers.hubspot.com/docs/methods/contacts/get_contacts. With your example, I was able to download little bit less than 1000 records. If I rewrite limit parameter from 1000 to 10,000 the result is same and it reach the limit of Hubspot API.

According to Hubspot documentation is possible to get next set of records by next call with parameter &vidOffset=X. We can do it manually and write 100 jobs with the particular parameter, but it would be better have some "fetch" option and go through pages programmatically not by writing hundreds of lines of code. Thanks for any help.

**Comment by kachnitel** [comment]
Hi zimami!
It should actually work, looking at the documentation, the `pagination` object in api config should look like this: 

```
      "pagination": {
        "method": "offset",
        "limit": 100,
        "limitParam": "count",
        "offsetParam": "vidOffset"
      }
```

Hope I'm reading the docs right, let me know how it goes!

**Comment by zimami** [comment]
Hi,
that's it. The problem was in <code>"offsetParam": "vidOffset"</code> Thanks for your help. It works great now.

**Comment by kachnitel** [comment]
Great to hear it worked!

**Comment by zimami** [comment]
Hi, one more thing I would like to ask. I went through our customer data, which I loaded according to parameters above and I realized that many of rows in KBC is duplicated. So I tried if it's same with Hubspot API Demo <code>https://api.hubapi.com/contacts/v1/lists/all/contacts/all?hapikey=demo</code> and for 92 423 contacts(vid) in this demo, KBC downloaded 307,856 rows different just in "profile_token", "profile_url", "identity_profiles". 
Can you please confirm, that this result is OK and this behaviour is right?
Thanks.

**Comment by kachnitel** [comment]
Alright, I've looked into the documentation once again and checked how the offset value in response matches up to `vid` values in each actual contact item, and realized the offset value needs to be taken from the response, not just by increasing the offset number.

That can be achieved using this config: 
```
{
  "pagination": {
    "method": "response.param",
    "responseParam": "vid-offset",
    "queryParam": "vidOffset",
    "includeParams": true
  }
}
```
