### ISSUE TITLE
No data => success?

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/generic-extractor#5]
Tohle by možná nemuselo bejt jako success?

![screen shot 2016-01-21 at 15 26 20](https://cloud.githubusercontent.com/assets/497675/12483101/62db6d86-c053-11e5-9f32-3e3a71645e51.png)

Konfigurace: 
```
{
  "parameters": {
    "api": {
      "baseUrl": "http://api.fixer.io/"
    },
    "config": {
      "outputBucket": "currency",
      "jobs": [
        {
          "endpoint": "latest",
          "dataType": "rates_test",
          "dataField": "root"
        }
      ]
    }
  }
}
```

**Comment by kachnitel** [comment]
Tohle je tezky, nenastal zadny error, a s inkrementalnim exportem z ruznych API muze nastat situace, ze nejsou zadna nova data. Nebo pri rekurzivnich volanich se muze bezne cyklit nad "potomky", kde nektere nevrati zadna data, a v takovych situacich by extractor nemel spadnout s chybou. 

Reseni me napada, dat k "job" flag, ze ma spadnout kdyz prijde nula dat, pripadne kdyz neexistuje objekt kde maji data byt - nyni kontroluje `empty()`, protoze ne vzdy se vrati prazdne pole, nekdy neprijde zadne, kdyz spravne nejsou zadna data. 

Problem je, ze bych takovy flag stejne defaultne nastavil tak, aby to prochazelo, a tim se asi nedocil kyzeneho erroru pri prvotni konfiguraci aplikace, coz je, predpokladam, cela pricina tehle issue?

**Comment by ondrejhlavacek** [comment]
V pohodě, díky moc za vysvětlení, rozumím tomu, nechal bych to bejt jak to je, pokud by se na to naráželo moc často, tak bych to řešil pak :-)
