### ISSUE TITLE
Parent ctor not called

### ISSUE THREAD

**Issue by odinuv** [keboola/generic-extractor#63]
Line   src/Keboola/GenericExtractor/Authentication/OAuth20Login.php
 ------ -----------------------------------------------------------------------------------------------------------
  39     Keboola\GenericExtractor\Authentication\OAuth20Login::__construct() does not call parent constructor from
         Keboola\GenericExtractor\Authentication\Login.

related to #54

**Comment by MiroCillik** [comment]
Fixed https://github.com/keboola/generic-extractor/commit/365c3bc628148ece52c784e1e7d9e0e5e3deca18#diff-c48be45929a07dde6a79b4089be8b281

Well, at least it doesn't throw a warning. The authentication classes should be refactored anyways.
