### ISSUE TITLE
Module command is broken

### ISSUE THREAD

**Issue by odinuv** [keboola/generic-extractor#64]
Line   src/Keboola/GenericExtractor/Command/ModuleCommand.php
 ------ ----------------------------------------------------------------------------------------
  45     Call to static method create() on an unknown class Keboola\Juicer\Filesystem\YamlFile.
  47     Call to static method create() on an unknown class Keboola\Juicer\Filesystem\YamlFile.

YamlFile does not exist at all, should we remove ModuleCommand completely?

**Comment by MiroCillik** [comment]
I don't know what the command is doing, but the `/config/modules.yml` has been changed to JSON, so maybe just use json_decode/json_encode, instead of YamlFile

**Comment by MiroCillik** [comment]
The only module, configured in `config/modules.yml`, is https://github.com/keboola/gex-get-response-array. This module consist of a single class with a single @deprecated method. 
I would suggest to get rid of this module thing?

**Comment by odinuv** [comment]
fixed in 4a592e6762d8c453bbafef5471d65d5993ad5cf9
