### ISSUE TITLE
Rename Jobs ->  Resources

### ISSUE THREAD

**Issue by Halama** [keboola/generic-extractor#7]
Pojmenování `Jobs` mi přijde matoucí protože jobs už říkáme něčemu jinému v KBC.
Přejměnoval bych to asi na `Resources`, imho to pak bude srozumitelnější i v UI.

Pozor na zpětnou kompatibilitu. Pro potomky v zanořených resources by to mohl být pojmenování možná jenom jako `children: []`

**Comment by odinuv** [comment]
@Halama Trvas na tom jeste? Imho se to s KBC zas tak moc netluce a nechal bych to jak to je, ale jestli to budem prejmenovavat, tak co nejdriv

**Comment by Halama** [comment]
za tu praci to asi nestoji. ale to pojmenovani jobs se mi teda moc nelibi.

**Comment by odinuv** [comment]
ja uz jsem si zvykl a nechal bych to jak to je :)

**Comment by Halama** [comment]
ok
