### ISSUE TITLE
Support for dataField separator configuration

### ISSUE THREAD

**Issue by ErikZigo** [keboola/generic-extractor#76]
U `dataField` v mappingu se v soucasne dobe pouziva tecka jako oddelovac cesty

`
{
"dataField": "path.to.resource"
}
`

Problem nastane, kdyz v nazvech jednotlivych uzlu jsou tecky. Idealni by bylo moznost konfigurace separatoru pro tu cestu. Napriklad tecku zmenit na |

`
{
"dataField": "path|to|my.resource"
}
`

**Comment by Halama** [comment]
nešlo by tam spíš použít http://jmespath.org/ To používá AWS SDK např. https://github.com/keboola/connection/blob/83279975330a6f54e749a3d0594a5dbc712f2f15/scripts/deploy.php#L36

**Comment by odinuv** [comment]
to by sice asi slo, ale znamenalo by to vsecko kompletne predelat

**Comment by odinuv** [comment]
fixed in 74cf9effea17df733bf1d71c1cd47323f807093b
