### ISSUE TITLE
Logging the requested urls

### ISSUE THREAD

**Issue by pocin** [keboola/generic-extractor#79]
Is there an option to log (without debug mode) the requested urls? i.e. 

something like this in config 
```
{
   ...
 "config": {
   "logUrls": true,
   ...
  }
}
```

would essentialy produce the same output as the debug mode does

```
2017-07-23 20:00:29] logger.DEBUG: GET /CheeseCounts?startTime=2017-07-13T00%3A00%3A00&endTime=2017-07-22T24%3A00%3A00&region=-1&user=barbar&pass=foobar&siteId=666&populationType=8 HTTP/1.1 Host: spam.meal.com Accept: application/json User-Agent: Guzzle/5.3.1 curl/7.38.0 PHP/7.1.7 [] []
```
without the other bells and whistles (deprecation warnings, ...)

Personally to me it doesn't make much sense, but it's a client request so I am checking with you what's your point of view. They want the url logging for monitoring purposes and to troubleshoot if something goes wrong.

**Comment by pocin** [comment]
Or maybe just log the value of elements of the `"params": {...}` config section when the job starts.

**Comment by odinuv** [comment]
That's exactly what the `debug` is for, so the answer is no. Is there something particular which bothers you in debug mode?

**Comment by odinuv** [comment]
the `params` section is what you see in the UI in configuration (except for encrypted values), what would be the use of that?

**Comment by pocin** [comment]
I think the debug mode is perfectly fine and I agree with you. I asked because I thought I might be missing something. Thanks
