### ISSUE TITLE
Enhance stopping strategy for pagination

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/generic-extractor#82]
Specifikovat část odpovědi, která se nemá měnit, aby došlo k zastavení stránkování. Magento má `pagenum` stránkování a při zvyšování stránek nad poslední vrací pořád tu samou odpověď jako u poslední stránky kromě jednoho pole, do kterýho dává číslo aktuální stránky. V tomhle případě by se řeklo, že pro zastavení stránkování se nemá měnit část odpovědi pod `items`:
![](https://slack-imgs.com/?c=1&url=https%3A%2F%2Fmonosnap.com%2Ffile%2FKel2Tz9lzzB4vKF6pU5G3B8oK3orCu.png)

**Comment by odinuv** [comment]
fixed by c9ced2d4e7ae5293ef67437975852d92256dc9ba
